### PR TITLE
Update windows download link

### PR DESCRIPTION
**Pull request by AdrianoCahete**

### CODE REVIEW

**Comment by wez** [comment]
thanks for digging in; can you amend the link to this version:

https://ci.appveyor.com/api/projects/wez/watchman/artifacts/watchman.zip?branch=master&job=Environment:+WATCHMAN_WIN7_COMPAT%3D&pr=false

**Comment by wez** [comment]
Ah, this is on the wrong branch.  The file to change is on master.  I'll update this in the right place and push it.

**Comment by AdrianoCahete** [comment]
The gh-pages branch isn't working anymore?

**Comment by AdrianoCahete** [comment]
#586

**Pull request closed without merging**
