### PR TITLE
Bump compiler requirement to C++14

### PR DESCRIPTION
**Pull request by wez**
Summary: It makes some things easier for us if we can use C++14
features, so let's see if our CI has these compilers ready to go.

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @sid0, @otrempe and @Vaelatern to be potential reviewers.

**Comment by facebook-github-bot-8** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/367/files/48899e14a8c7f485e4453b1f378663cc8d6bcdce..8d06f8f944c661743aee3345aa7341ec1738d36a)

**Comment by facebook-github-bot-0** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/367/files/8d06f8f944c661743aee3345aa7341ec1738d36a..9279c5fd8daf0a7b68e211aca96715afedf2228a)

**Comment by facebook-github-bot-9** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/367/files/9279c5fd8daf0a7b68e211aca96715afedf2228a..f398fc12fb3627d816e8fb75c24bc8f1dd11c3f3)

**Comment by wez** [comment]
The verdict is that there are enough changes to handle in the windows compiler upgrade that it may not be worth doing this right now

**Pull request closed without merging**
