### PR TITLE
FreeBSD patch

### PR DESCRIPTION
**Pull request by yurivict**

### CODE REVIEW

**Comment by wez** [comment]
Thanks for looking at this!

https://github.com/facebook/watchman/pull/634 was an earlier attempt to make the FreeBSD build happier, but it was abandoned.

Our stance on FreeBSD support is that it's probably always going to be broken without CI (for long term sustainability) and a champion for tactical maintenance.

If we have CI that runs on each change then we can make a best effort not to break it, but without that it's likely going to get broken on any arbitrary future change.

Last time I looked, there was no FreeBSD CI.  Has that changed?

To make things a bit more awkward for you at the moment: in our internal builds we've switched to a new builder that fetches and builds (quite frankly, the very heavyweight) folly and other deps.   We haven't had bandwidth to make that work on the open source CI yet (https://github.com/facebook/watchman/pull/706 is the somewhat sorry state of that).

**Comment by yurivict** [comment]
This is just a small patch that I found to be needed while updating the port in order for it to build. Th port is updated now.

The larger issue of FreeBSD CI is a different story. I am not sure how do you run CI, is it run on the company servers?

**Comment by wez** [comment]
We use a mixture of internal CI and public CI.  We're unlikely to ever add FreeBSD to our internal CI.  If there was a public FreeBSD CI service that we could use, and someone was willing to put in some cycles to getting that configured so that it runs on pull requests and periodically on master, that would help us keep things working for FreeBSD.

**Comment by yurivict** [comment]
I will research the larger issue of FreeBSD CI and will keep ```watchman``` in mind.

Regarding this PR, I think you should merge it because it's just one simple and obvious patch, and watchman now builds and passes tests on FreeBSD:
```
===>  Testing for watchman-4.9.0.1115
[1/1] cd /usr/ports/sysutils/watchman/work/.build && /usr/local/bin/ctest
Test project /usr/ports/sysutils/watchman/work/.build
      Start  1: art
 1/11 Test  #1: art ..............................   Passed    0.63 sec
      Start  2: ignore
 2/11 Test  #2: ignore ...........................   Passed    2.96 sec
      Start  3: pending
 3/11 Test  #3: pending ..........................   Passed    0.47 sec
      Start  4: string
 4/11 Test  #4: string ...........................   Passed    0.02 sec
      Start  5: log
 5/11 Test  #5: log ..............................   Passed    0.02 sec
      Start  6: bser
 6/11 Test  #6: bser .............................   Passed    0.03 sec
      Start  7: wildmatch
 7/11 Test  #7: wildmatch ........................   Passed    0.03 sec
      Start  8: childproc
 8/11 Test  #8: childproc ........................   Passed    2.40 sec
      Start  9: result
 9/11 Test  #9: result ...........................   Passed    0.02 sec
      Start 10: cache
10/11 Test #10: cache ............................   Passed    0.02 sec
      Start 11: MapUtilTest
11/11 Test #11: MapUtilTest ......................   Passed    0.02 sec

100% tests passed, 0 tests failed out of 11

Total Test time (real) =   6.62 sec
```

**Comment by yurivict** [comment]
FYI: Cirrus CI says that it supports FreeBSD: https://cirrus-ci.org/guide/FreeBSD/

**Pull request closed without merging**
