### PR TITLE
Testwinbuild

### PR DESCRIPTION
**Pull request by wez**
Checking that visual studio 2015 compiler bump works in appveyor.
This has been checked in a local vm

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @dhruvsinghal and @Vaelatern to be potential reviewers.

**Comment by facebook-github-bot-0** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/370/files/f0643affac8129c6d284470b40c7f357852210e7..74ecc78214a7b1c4eb2ef0800c8084dd4c75cecc)

**Comment by facebook-github-bot-2** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/370/files/74ecc78214a7b1c4eb2ef0800c8084dd4c75cecc..3c297df8323996418955ca2b8d12f87a401815a5)

**Comment by facebook-github-bot-9** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/370/files/3c297df8323996418955ca2b8d12f87a401815a5..2f68fb2ec4d26432167bba366386486bd8870b54)

**Comment by facebook-github-bot-3** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/370/files/2f68fb2ec4d26432167bba366386486bd8870b54..658e7e729157cd1b7b4427db94ada38e246e6791)

**Comment by facebook-github-bot-0** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/370/files/658e7e729157cd1b7b4427db94ada38e246e6791..bffd172cb1eb0a7194105ca9296cdd7586264241)

**Comment by facebook-github-bot-7** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/370/files/bffd172cb1eb0a7194105ca9296cdd7586264241..97a22ae9a1f40fba63703cfe4312446fb33599f7)

**Comment by facebook-github-bot-3** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/370/files/97a22ae9a1f40fba63703cfe4312446fb33599f7..1a0fe76e35af02693a595d01043c104326b431b3)

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/370/files/1a0fe76e35af02693a595d01043c104326b431b3..1d9b46637cb436e78a222fb77e5b22568617e305)

**Comment by facebook-github-bot-3** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/370/files/1d9b46637cb436e78a222fb77e5b22568617e305..8db4cba2bea2220f4d44b697b9679d82e5919ab2)

**Comment by facebook-github-bot-2** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/370/files/8db4cba2bea2220f4d44b697b9679d82e5919ab2..993facc6b2fa80d43372247f9432a98fe317d12c)

**Pull request closed without merging**
