### PR TITLE
updates to README.md

### PR DESCRIPTION
**Pull request by mcprentiss**
spelling fix

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @wez to be a potential reviewer.

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by sid0** [comment]
This is an issue with the readme of a third-party library, so I think this fix should go upstream.

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by sid0** [comment]
I think https://github.com/armon/libart is the library.

**Comment by mcprentiss** [comment]
Ha. I sent them a pull requests for the fix.

**Comment by mcprentiss** [comment]
This fix has been merged by upstream.  It should be ready now.

**Comment by wez** [comment]
Thanks! pushed as 2095301ec877590f6cee49884fe7a66628959c6b

**Pull request closed without merging**
