### PR TITLE
Add var to `cap_versions`.

### PR DESCRIPTION
**Pull request by cpojer**

### CODE REVIEW

**Comment by cpojer** [comment]
node 4 is having trouble with this and doesn't let me run the tests :(

**Comment by amasad** [comment]
Can you add `use strict` to make sure there aren't more things like this?

**Comment by amasad** [comment]
Failure doesn't seem to be related. Is there anyway we can restart it?

**Comment by wez** [comment]
I've kicked it

**Comment by wez** [comment]
https://travis-ci.org/facebook/watchman/jobs/96389195#L2761

**Comment by amasad** [comment]
Needs another `var` https://github.com/facebook/watchman/blob/a75b2b8b74b57382ce9bfa5de6695537e1040912/node/index.js#L267

**Comment by cpojer** [comment]
done.

**Comment by wez** [comment]
If you run `make integration`, you can save some round-trips in the PR :-)
https://facebook.github.io/watchman/contributing.html#getting-started

**Comment by cpojer** [comment]
yeah, I'm sorry, I thought it would be a simple fix and I didn't actually clone the repo and was hoping that the travis tests will catch all the issues #fridaynighthacking.

**Comment by cpojer** [comment]
@wez finally updated! The remaining test failure seems unrelated to the JS changes.

**Comment by amasad** [comment]
Can we merge this?

**Comment by wez** [comment]
Sorry for the delay; just got back from PTO today.  The windows failure seems unrelated, so I pushed this as 36d4b347715f328f7e2802a0495daa0d7de5af04.

Do you need me to bump the npm package too?

**Comment by wez** [comment]
Published as version 1.7.0

**Pull request closed without merging**
