### PR TITLE
Added raw JSON-to-BSER comparison tests.

### PR DESCRIPTION
**Pull request by dhruvsinghal**

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @sid0 to be a potential reviewer.

**Comment by sid0** [comment]
Thanks -- I'll land this once 4.6.0 is cut.

Could you also add the same tests on the Python side?

**Comment by facebook-github-bot-4** [comment]
@dhruvsinghal updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@dhruvsinghal updated the pull request.

**Pull request closed without merging**
