### PR TITLE
Fixing Travis build, remove OS X, up to 18.04

### LINKED ISSUE #752: Travis build failures
Travis builds for `master` are red for a long time https://travis-ci.org/facebook/watchman/builds Does that mean that `watchman` builds are broken on Linux?

**EDIT**: The build was broken in [Feb 2019](https://github.com/facebook/watchman/commits/master?after=658e9ec680fe7691e1fe1d136180b282511a301a+925) - most likely by https://github.com/facebook/watchman/commit/631bdda241a136d975883de7d78aacce59dc0721.

### PR DESCRIPTION
**Pull request by abitrolly**
Just a test to see if it could fix #752

Ref. https://docs.travis-ci.com/user/reference/bionic/

### CODE REVIEW

**Comment by wez** [comment]
Thanks for looking at this! However, we're standardizing on Github Actions and will be removing the other CI configs (the others are too flakey, too slow and have build timeouts that are too low to build our full feature set).

We need to revise instructions on how to manually build things, but the gist of it is that you can run:

```
./build/fbcode_builder/getdeps.py build watchman
mkdir /tmp/install-root
./build/fbcode_builder/getdeps.py fixup-dyn-deps watchman /tmp/install-root
```

to build and deploy the executables under `/tmp/install-root`

**Comment by abitrolly** [comment]
Indeed. Travis could not complete because of timeout.
Is it possible to run GitHub Actions locally? 

I was using instruction from https://facebook.github.io/watchman/docs/install.html#installing-from-source - there is no other way to install on Linus except installing all dependencies and compiling everything. Much better UX is to provide Linux binaries for download.

**Comment by wez** [comment]
> I was using instruction from https://facebook.github.io/watchman/docs/install.html#installing-from-source - there is no other way to install on Linus except installing all dependencies and compiling everything. Much better UX is to provide Linux binaries for download.

With GH actions we do now have the ability to offer linux binaries.  It's a bit clunky, but here's how to get to them:

1. View list of passing builds at
https://github.com/facebook/watchman/actions?query=is%3Acompleted+event%3Apush+is%3Asuccess
2. Click on the most recent one
3. In the top right corner there is an "Artifacts" drop down; click it and it will show you a "watchman" download (see https://github.com/actions/upload-artifact/issues/2)
4. Inside that zip file you'll find binaries for all three platforms

I'd like to see this streamlined in the future but it depends on https://github.com/actions/upload-artifact/issues/21

**Comment by abitrolly** [comment]
172Mb for Linux binary. That's huge to be run as a resident process compared, for example, to `watchexec` which is only 3Mb. 

I see there are now updated instructions. https://facebook.github.io/watchman/docs/install.html#binary-downloads-for-linux-macos-and-windows-beta That's nice.

**Pull request closed without merging**
