### PR TITLE
Prepping for C++11 bits

### PR DESCRIPTION
**Pull request by wez**

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/4e9b34fdb29fe9453dc1b99d7e507f628584b629..992bc4164c2fbc749d1e1400207bd3566da37e02)

**Comment by facebook-github-bot-6** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/992bc4164c2fbc749d1e1400207bd3566da37e02..7537172f7490e20a74ec62d9c01334a726257783)

**Comment by facebook-github-bot-5** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/7537172f7490e20a74ec62d9c01334a726257783..391a3ed34859b8c9b88f44ffa7e16089c3bf6a0c)

**Comment by facebook-github-bot-9** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/391a3ed34859b8c9b88f44ffa7e16089c3bf6a0c..db076db19fb6d4ca23697c16f277319147c01a5c)

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/db076db19fb6d4ca23697c16f277319147c01a5c..700d64c1707be190c5b0cb5528d8bde2816bede1)

**Comment by facebook-github-bot-5** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/700d64c1707be190c5b0cb5528d8bde2816bede1..43e797b0846d8534f940facf04eb2aa2955cf3e4)

**Comment by facebook-github-bot-6** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/43e797b0846d8534f940facf04eb2aa2955cf3e4..b326f3f92f65633f0cdcbf165deaeca3858c9632)

**Comment by facebook-github-bot-7** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/b326f3f92f65633f0cdcbf165deaeca3858c9632..77ed008daa3320e96477212b429d10d6c03c4c78)

**Comment by facebook-github-bot-2** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/77ed008daa3320e96477212b429d10d6c03c4c78..68f678c332ec818e6fc5e724be75390521b3fe16)

**Comment by facebook-github-bot-8** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/68f678c332ec818e6fc5e724be75390521b3fe16..29323938953f6e8310e10ddbfba356fdb4e16b04)

**Comment by facebook-github-bot-1** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/29323938953f6e8310e10ddbfba356fdb4e16b04..3c8001601c48e559784128269a3d5fedcafd307f)

**Comment by facebook-github-bot-3** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/3c8001601c48e559784128269a3d5fedcafd307f..ac5f4b591b491e6c2881059307610eec3553b6f1)

**Comment by facebook-github-bot-0** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/ac5f4b591b491e6c2881059307610eec3553b6f1..ec700901ec534db86f2f55994ded0b91ed0ec6ee)

**Comment by facebook-github-bot-2** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/ec700901ec534db86f2f55994ded0b91ed0ec6ee..ae419f5e59d06c590561506e18f129ceda8f4386)

**Comment by facebook-github-bot-8** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/ae419f5e59d06c590561506e18f129ceda8f4386..19fd79ef756583de75d73d8e3e61854aacf8bc3c)

**Comment by facebook-github-bot-1** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/19fd79ef756583de75d73d8e3e61854aacf8bc3c..ff82b7f0584092bb00bce605a82132d8e357b045)

**Comment by facebook-github-bot-9** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/ff82b7f0584092bb00bce605a82132d8e357b045..0573e39cc7177a292da6028174be5d439b78f803)

**Comment by facebook-github-bot-7** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/0573e39cc7177a292da6028174be5d439b78f803..5c65f58e549470a29224c91eef512825625dd829)

**Comment by facebook-github-bot-3** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/5c65f58e549470a29224c91eef512825625dd829..063b397a2a8435e18d2570cfe7e661593ae7e5fb)

**Comment by facebook-github-bot-6** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/063b397a2a8435e18d2570cfe7e661593ae7e5fb..327b820e0a712df69aea8a3f8de02a7552538a3a)

**Comment by facebook-github-bot-1** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/327b820e0a712df69aea8a3f8de02a7552538a3a..59e2b73e1a55da1c96f067db08bd844a1ec6403d)

**Comment by facebook-github-bot-5** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/fb70a0768aec8320793f3284fd95a40857931554..c2be16f13cbb3f40d23cb24f959f49ec5b8ef390)

**Comment by facebook-github-bot-0** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/c2be16f13cbb3f40d23cb24f959f49ec5b8ef390..f7d99e5e7ae7a7ec72531a4185fc383d937003f0)

**Comment by facebook-github-bot-6** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/f7d99e5e7ae7a7ec72531a4185fc383d937003f0..d579040050d98050a1f5c9e7136fa3476339b445)

**Comment by facebook-github-bot-9** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/d579040050d98050a1f5c9e7136fa3476339b445..44f55383c276fb4d1375735e6958dc172aae62fe)

**Comment by facebook-github-bot-8** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/44f55383c276fb4d1375735e6958dc172aae62fe..846b9c6fc38615865fd8516f4bce829efef6f09e)

**Comment by facebook-github-bot-8** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/846b9c6fc38615865fd8516f4bce829efef6f09e..0aa54ee402d52677cfc8f8f1d0e0fd9319a03c19)

**Comment by facebook-github-bot-9** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/0aa54ee402d52677cfc8f8f1d0e0fd9319a03c19..3fb8f41a4424da8dc53a72d757ff82250935d051)

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/354/files/3fb8f41a4424da8dc53a72d757ff82250935d051..b6c372ee6062996af9aaf074735a3381c43675a3) - [changes since last import](https://github.com/facebook/watchman/pull/354/files/3fb8f41a4424da8dc53a72d757ff82250935d051..b6c372ee6062996af9aaf074735a3381c43675a3)

**Pull request closed without merging**
