### PR TITLE
add glob generator

### PR DESCRIPTION
**Pull request by wez**

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @dhruvsinghal and @sid0 to be potential reviewers.

**Comment by facebook-github-bot-7** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/344/files/ed50dc004a303797183aeea8bf8b04b5b7c07bf2..574258180f5865869b2413a739d2be243bcca42c)

**Comment by facebook-github-bot-9** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/344/files/574258180f5865869b2413a739d2be243bcca42c..93b78488d4f6987bb6a39967c943a3fd051871ec)

**Comment by facebook-github-bot-9** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/344/files/c35d79136c7d74bd7a222a440d890422ea296ac4..07e7061871536bb90734ce5c014db995da59e503)

**Comment by facebook-github-bot-6** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/344/files/07e7061871536bb90734ce5c014db995da59e503..a700eb17e62ea1b46bed926e68cd1d55e16f02c4)

**Comment by wez** [comment]
Pushed as fb68398

**Pull request closed without merging**
