### PR TITLE
migrate find.php -> test_find.py

### PR DESCRIPTION
**Pull request by wez**

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/343/files/b8b0fb8b78efd6e1d61a7b79c0e7fd1a30414977..806905d39c6b056e8ee4384d6a18dab6712b9dc1)

**Comment by facebook-github-bot-7** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/343/files/806905d39c6b056e8ee4384d6a18dab6712b9dc1..5af84cdeb4d252960d993be1a3f9fbe7786ea4b0)

**Comment by facebook-github-bot-5** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/343/files/5af84cdeb4d252960d993be1a3f9fbe7786ea4b0..0248ab3a28a7a3c6e7e613f197cf24d362c4a6f0)

**Comment by facebook-github-bot-2** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/343/files/0248ab3a28a7a3c6e7e613f197cf24d362c4a6f0..1ff2dc803ebeda96b69895e5a81fa299549c6b29)

**Comment by facebook-github-bot-9** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/343/files/1ff2dc803ebeda96b69895e5a81fa299549c6b29..29a62bbfc6da0a1864474ff348d7533d94484ce7)

**Comment by facebook-github-bot-9** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/343/files/29a62bbfc6da0a1864474ff348d7533d94484ce7..d730990edfef5bf33b912e05babf6a367a47f5d6)

**Pull request merged**
