### PR TITLE
Crazy? baby step towards adopting C++11

### PR DESCRIPTION
**Pull request by wez**
In looking at the next generation index stuff, I wanted to define type safe vectors, maps and sets so that we can have the compiler catch any silly mistakes as the code becomes more complex.

I took a stab at doing something with macros and inline functions in C for vectors (the simplest container) and realized that by the time that I would have been able to apply this to the other container types, I would have basically implemented C++ in C, and done it poorly.

So, this PR is the most basic C -> C++11 translation: the very large majority of this code is just C that the C++ accepts with its more strict typing.  Each commit in this PR targets migrating a single file at a time.

My intention is to let the CI think about this and shake out where we might need some compiler specific stuff to make sure that C++11 is really available to us.

With that proven, there are a couple of conceptually light refactorings that I'd like to make to clean up ownership semantics of the roots and the structures that they track so that we can use typed containers in our follow on work.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request.

**Comment by wez** [comment]
The travis failures are for two rows in the build matrix that are not set to use gcc-5.  For those to work we need to get them on gcc 4.8 and up.  I'm not sure what the best way of expressing that in the travis configuration is, so I've left it for the moment.  Any thoughts on that @sid0 ?  It translates to setting GCC=g++-4.8 in the environment for those jobs

**Pull request closed without merging**
