### PR TITLE
Add js name to fenced code blocks

### PR DESCRIPTION
**Pull request by kevinsawicki**
Allows the code inside them to be syntax highlighted in various places like [GitHub](https://github.com/kevinsawicki/watchman/blob/patch-1/node/README.md#usage) and in [Atom](https://atom.io)

### CODE REVIEW

**Comment by kevinsawicki** [comment]
>  In order for us to review and merge your code, please sign up at https://code.facebook.com/cla 

Done :+1:

**Comment by wez** [comment]
Thanks!  Can you double check that it renders ok if you launch the website locally?
Details here:

http://facebook.github.io/watchman/contributing.html#don-t-forget-the-docs

**Comment by wez** [comment]
... I don't think concurrently try to render that page in the website so that may be a waste of time

**Comment by kevinsawicki** [comment]
>  I don't think concurrently try to render that page in the website so that may be a waste of time

Yeah, ran the docs site and explored them a bit, didn't see this README anywhere though.

**Comment by wez** [comment]
Applied via `hub am https://github.com/facebook/watchman/pull/128`.  Thanks!

**Pull request closed without merging**
