### PR TITLE
do not leak memory when printing command list

### PR DESCRIPTION
**Pull request by zined**

### CODE REVIEW

**Comment by sid0** [comment]
Thanks! How did you detect this?

How hard do you think it'll be to add a test such that ASAN/LSAN catches this?

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by zined** [comment]
i came from https://facebook.github.io/react-native/docs/getting-started.html, reached the 'Highly Recommended Installs' part, cloned watchman, took a look at some code, had a gut feeling to build with `-fsanitize=address`, saw a few exotic reads in the hashing part in v4.5.0, found the valgrind "integration", just stumbled into it. As i've seen you're last commits are related to memory management, I thought you'd be happy to have this one, too. Can't tell anything on the scope of automatically having caught this, as I haven't really looked deeper into anything.

**Comment by facebook-github-bot-9** [comment]
@zined updated the pull request.

**Comment by sid0** [comment]
Pushed as 86ef97d69cfbfd760ea38ba5b6b9fb95059b6fe5, thanks!

**Pull request closed without merging**
