### PR TITLE
Update link to BSER (CLA not needed)

### PR DESCRIPTION
**Pull request by sandstrom**

### CODE REVIEW

**Comment by sandstrom** [comment]
No CLA is required if the change is trivial, as is the case here.

**Comment by sandstrom** [comment]
@wez Our of curiosity, why did you close this?

**Comment by wez** [comment]
sorry, meant to add a comment that this was fixed in https://github.com/facebook/watchman/commit/8118a56c3f65786735922f3f6ad2e1fb88269f70

**Comment by sandstrom** [comment]
@wez Great, happy to hear!

Too bad the CLA-legalse gated this. Most CLA-policies will permit minor stuff without requiring complicated paperwork, since there is no copyright on trivial stuff anyways.

**Pull request closed without merging**
