### PR TITLE
Improve the wording for root_restrict errors.

### PR DESCRIPTION
**Pull request by wez**
Also took the opportunity to port the PHP test to python.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
By analyzing the blame information on this pull request, we identified @sid0 and @dhruvsinghal to be potential reviewers.

**Comment by facebook-github-bot-1** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/335/files/7e49fe931b17e8be48242ba54fff6bec754bb6fa..e7ea6a5f371b932753c1325afcec72f2ec0e9ffb)

**Comment by facebook-github-bot-9** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/335/files/e7ea6a5f371b932753c1325afcec72f2ec0e9ffb..747e7e61c12ad35b6a330781a735e512eb4efa8a)

**Comment by facebook-github-bot-4** [comment]
@wez updated the pull request - [view changes](https://github.com/facebook/watchman/pull/335/files/747e7e61c12ad35b6a330781a735e512eb4efa8a..b27fe7226054c745abd048b1904e7ed4e39b5b75)

**Comment by wez** [comment]
Pushed as 973a708

**Pull request closed without merging**
